theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1_add_before: 
  - h2
  - h3
  - h4
  - separator
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
plugins:
  - table
  - fullscreen
  - image
  - textcolor
  - link
  - code
  - autoresize
#  - advimage
#  - heading
heading_clear_tag: p
width: "100%"
content_css: "/assets/tinymce.css"
toolbar: 
  - styleselect | bold boldred_btn italic forecolor | list link image table | undo redo | fullscreen code
formats:
  boldred: {selector: "p",block: "p", classes: "mc-important"}
setup: function(ed) {
       ed.addButton('boldred_btn', {title:'Bold-Red',icon:"fa fa-red fa-bold", onclick:function() {ed.focus();ed.formatter.toggle('boldred'); }}); 
      }
