
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1_add_before: 
  - h1
  - h2
  - h3
  - separator
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
plugins:
  - table
  - fullscreen
  - advimage
  - heading
heading_clear_tag: p
